# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ANAS.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ANAS(object):
    def setupUi(self, ANAS):
        ANAS.setObjectName("ANAS")
        ANAS.resize(1380, 750)
        ANAS.setMinimumSize(QtCore.QSize(1350, 750))
        ANAS.setMaximumSize(QtCore.QSize(1380, 800))
        self.centralwidget = QtWidgets.QWidget(ANAS)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 10, 471, 361))
        self.bg_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(490, 10, 561, 361))
        self.bg_3.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.gfi_1 = QtWidgets.QLabel(self.centralwidget)
        self.gfi_1.setGeometry(QtCore.QRect(20, 20, 451, 341))
        self.gfi_1.setText("")
        self.gfi_1.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/B.G/Iron_Template_1.gif"))
        self.gfi_1.setScaledContents(True)
        self.gfi_1.setObjectName("gfi_1")

        self.gfi2 = QtWidgets.QLabel(self.centralwidget)
        self.gfi2.setGeometry(QtCore.QRect(500, 20, 541, 341))
        self.gfi2.setText("")
        self.gfi2.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/ExtraGui/live.gif"))
        self.gfi2.setScaledContents(True)
        self.gfi2.setObjectName("gfi2")

        self.gif3 = QtWidgets.QLabel(self.centralwidget)
        self.gif3.setGeometry(QtCore.QRect(10, 380, 441, 331))
        self.gif3.setText("")
        self.gif3.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/VoiceReg/__1.gif"))
        self.gif3.setScaledContents(True)
        self.gif3.setObjectName("gif3")

        self.gif5 = QtWidgets.QLabel(self.centralwidget)
        self.gif5.setGeometry(QtCore.QRect(450, 380, 521, 241))
        self.gif5.setText("")
        self.gif5.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/ExtraGui/initial.gif"))
        self.gif5.setScaledContents(True)
        self.gif5.setObjectName("gif5")

        self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(1140, 660, 211, 51))
        self.text_time.setStyleSheet("background-color: transpreant;\n""border-radius:none")
        self.text_time.setObjectName("text_time")

        self.text_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_Date.setGeometry(QtCore.QRect(1130, 580, 221, 61))
        self.text_Date.setStyleSheet("background-color: transpreant;\n""border-radius:none")
        self.text_Date.setObjectName("text_Date")

        self.text_Temp = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_Temp.setGeometry(QtCore.QRect(1120, 500, 241, 51))
        self.text_Temp.setStyleSheet("background-color: transpreant;\n""border-radius:none")
        self.text_Temp.setObjectName("text_Temp")

        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(1110, 650, 261, 71))
        self.bg_7.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/B.G/gggf.jpg"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")

        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(1140, 250, 231, 151))
        self.bg_5.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")

        self.pushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(1150, 330, 211, 61))
        self.pushButtonStart.setStyleSheet("\n"
"font: 22pt \"Courier\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(85, 85, 255);")
        self.pushButtonStart.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonStart.setShortcut("")
        self.pushButtonStart.setObjectName("pushButtonStart")
        



        self.pushButtonStop_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStop_2.setGeometry(QtCore.QRect(1150, 260, 211, 61))
        self.pushButtonStop_2.setStyleSheet("\n"
"font: 22pt \"Courier\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(85, 85, 255);")
        self.pushButtonStop_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonStop_2.setShortcut("")
        self.pushButtonStop_2.setObjectName("pushButtonStop_2")



        self.bg1 = QtWidgets.QLabel(self.centralwidget)
        self.bg1.setGeometry(QtCore.QRect(-30, 10, 1581, 801))
        self.bg1.setText("")
        self.bg1.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/B.G/Black_Template.jpg"))
        self.bg1.setScaledContents(True)
        self.bg1.setObjectName("bg1")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(1060, 10, 311, 231))
        self.bg_4.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")
        
        self.gif4_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif4_2.setGeometry(QtCore.QRect(1070, 20, 291, 211))
        self.gif4_2.setText("")
        self.gif4_2.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/ExtraGui/Earth.gif"))
        self.gif4_2.setScaledContents(True)
        self.gif4_2.setObjectName("gif4_2")

        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(1110, 410, 261, 71))
        self.bg_6.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/B.G/gggf.jpg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.bg_9 = QtWidgets.QLabel(self.centralwidget)
        self.bg_9.setGeometry(QtCore.QRect(1110, 570, 261, 71))
        self.bg_9.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_9.setText("")
        self.bg_9.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/B.G/gggf.jpg"))
        self.bg_9.setScaledContents(True)
        self.bg_9.setObjectName("bg_9")
        self.bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.bg_8.setGeometry(QtCore.QRect(1110, 490, 261, 71))
        self.bg_8.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bg_8.setText("")
        self.bg_8.setPixmap(QtGui.QPixmap("G.U.I Material-20210522T162824Z-001/G.U.I Material/B.G/gggf.jpg"))
        self.bg_8.setScaledContents(True)
        self.bg_8.setObjectName("bg_8")
        self.bg1.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.gfi_1.raise_()
        self.gfi2.raise_()
        self.gif3.raise_()
        self.gif5.raise_()
        self.text_time.raise_()
        self.text_Date.raise_()
        self.text_Temp.raise_()
        self.bg_7.raise_()
        self.bg_5.raise_()
        self.pushButtonStart.raise_()
        self.pushButtonStop_2.raise_()
        self.bg_4.raise_()
        self.gif4_2.raise_()
        self.bg_6.raise_()
        self.bg_9.raise_()
        self.bg_8.raise_()
        ANAS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ANAS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 21))
        self.menubar.setObjectName("menubar")
        ANAS.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(ANAS)
        self.statusBar.setObjectName("statusBar")
        ANAS.setStatusBar(self.statusBar)

        self.retranslateUi(ANAS)
        QtCore.QMetaObject.connectSlotsByName(ANAS)

    def retranslateUi(self, ANAS):
        _translate = QtCore.QCoreApplication.translate
        ANAS.setWindowTitle(_translate("ANAS", "MainWindow"))
        self.text_Date.setHtml(_translate("ANAS", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButtonStart.setText(_translate("ANAS", "START"))
        self.pushButtonStop_2.setText(_translate("ANAS", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ANAS = QtWidgets.QMainWindow()
    ui = Ui_ANAS()
    ui.setupUi(ANAS)
    ANAS.show()
    sys.exit(app.exec_())
